x86:
	gcc -pthread mt_instructionrate.c x86_mt_instructionrate.s ../Common/timing.c -o x86_mt_instructionrate
aarch64:
	gcc -pthread mt_instructionrate.c arm_mt_instructionrate.s ../Common/timing.c -o arm_mt_instructionrate
